### PR TITLE
DO NOT MERGE! Please publish the script you used to create this repository

### PR DESCRIPTION
**Pull request by kb-1000**
I want you to do this because I'm missing `mobile/jdk` and `mobile/jdk9` and there's no issue tracker.

### CODE REVIEW

**Comment by dmlloyd** [comment]
My email address is public in my profile. ;)

That said, you really don't want my scripts; they're horrible.  But it's all based on the ``git hg`` tool which can be found here: https://github.com/cosmin/git-hg

**Comment by kb-1000** [comment]
@dmlloyd but what's about these repositories now?

**Comment by dmlloyd** [comment]
I just have a cron which does ``git hg fetch`` and then pushes up the result.  Are you requesting that I add these repositories?  I'm not adding any new repositories which are not combined (like JDK10+) because it is too much of a pain.

**Comment by kb-1000** [comment]
@dmlloyd yes, I'm requesting this because `hg` only fails for me when using the server from openjdk, but others work well.

**Pull request closed without merging**
